services:
  - docker

script:
 #build
 - docker build -t udagram-api-feed ./udagram-api-feed
 - docker build -t udagram-api-user ./udagram-api-user
 - docker build -t udagram-api-frontend ./udagram-api-frontend
 - docker build -t udagram-api-reverseproxy ./udagram-api-reverseproxy

after_success: 
 # Tagging
 - docker tag udagram-api-feed huma23/udagram-api-feed:v1
 - docker tag udagram-api-user huma23/udagram-api-user:v1
 - docker tag udagram-api-frontend huma23/udagram-api-frontend:v1
 - docker tag udagram-api-reverseproxy huma23/udagram-api-reverseproxy:v1

 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - docker push huma23/udagram-api-feed:v1
 - docker push huma23/udagram-api-user:v1
 - docker push huma23/udagram-api-frontend:v1
 - docker push huma23/udagram-api-reverseproxy:v1